package com.example.auth;

import org.example.crud.usuarios.model.User;
import org.junit.jupiter.api.Test;
import org.springframework.security.crypto.bcrypt.BCrypt;

import static org.junit.jupiter.api.Assertions.*;

public class UserTest {
    @Test
    public void testHashPassword() {
        String password = "SenhaSegura123";
        String actualHash = User.hashPassword(password);

        assertNotNull(actualHash);
        assertFalse(actualHash.isEmpty());

        // Since the salt is random, we cannot directly compare the entire hash
        // But, we can verify that the actual hash starts with the prefix generated by BCrypt.gensalt
        String saltPrefix = BCrypt.gensalt(12).substring(0, 29); // Assuming "$2a$" is the prefix
        assertTrue(actualHash.startsWith(saltPrefix));
    }
}
